"""
Domain events: the in-process, strongly-typed facts a service emits when
something in the Nursery/Branch/Employee lifecycle happens
(`NurseryCreated`, `BranchUpdated`, `EmployeeInvited`, ...), and the
`DomainEventPublisher` that persists them to the `domain_events` outbox
table (`app/models/events.py`).

Kept in their own package (not `app/services/`) because a domain event is
a data definition every future module's services will also emit
(`PlantRegistered`, `SaleCompleted`, ...) — it's not itself business
logic, so it shouldn't live inside Module 4's own service module.

Deliberately separate from the SQLAlchemy `DomainEvent` model
(`app/models/events.py`) it gets persisted as: these are plain, frozen
dataclasses with zero ORM/session/HTTP dependencies, so a service's
"what happened" logic is unit-testable (assert the right event object was
built, with the right fields) without touching a repository or database
at all. `DomainEventPublisher` is the one place that translates an event
object into the persisted row shape.
"""
from app.domain_events.events import (  # noqa: F401
    AIPredictionGenerated,
    AIPredictionGeneratedForBranch,
    AIRecommendationActedUpon,
    AIRecommendationDismissed,
    AIRecommendationGenerated,
    AssistantActionCancelled,
    AssistantActionConfirmed,
    AssistantActionProposed,
    AssistantConversationStarted,
    AssistantMessageSent,
    BaseDomainEvent,
    BranchArchived,
    BranchCreated,
    BranchUpdated,
    CustomerCreated,
    CustomerUpdated,
    DiseaseDetected,
    DiseaseReportUpdated,
    EmailVerificationRequested,
    EmployeeActivated,
    EmployeeInvited,
    EmployeeRemoved,
    EmployeeTransferred,
    EnvironmentalRecorded,
    FertilizerRecorded,
    GrowthRecorded,
    HealthRecorded,
    InventoryArchived,
    InventoryLocationCreated,
    InventoryMovementRecorded,
    InvoiceGenerated,
    NurseryArchived,
    NurseryCreated,
    NurseryUpdated,
    OrderCreated,
    OrderStatusChanged,
    PassportGenerated,
    PasswordResetRequested,
    PaymentReceived,
    PlantArchived,
    PlantImageUploaded,
    PlantMoved,
    PlantRegistered,
    PlantReturned,
    PlantSold,
    PlantStatusChanged,
    PlantUpdated,
    PlantVarietyCreated,
    PlantVarietyDeleted,
    PlantVarietyUpdated,
    QRGenerated,
    QuotationCreated,
    QuotationStatusChanged,
    RefundProcessed,
    ReportFailed,
    ReportGenerated,
    ReservationCreated,
    ReservationExpiringSoon,
    ReservationReleased,
    SpeciesCreated,
    SpeciesDeleted,
    SpeciesUpdated,
    StockAdjusted,
    StockDamaged,
    StockDisposed,
    StockReceived,
    StockReleased,
    StockReserved,
    StockSold,
    StockTransferred,
    SystemAlertRaised,
    TreatmentApplied,
    WateringRecorded,
)
from app.domain_events.dispatcher import EventDispatcher, EventHandler  # noqa: F401
from app.domain_events.publisher import DomainEventPublisher  # noqa: F401

__all__ = [
    "BaseDomainEvent",
    "NurseryCreated",
    "NurseryUpdated",
    "NurseryArchived",
    "BranchCreated",
    "BranchUpdated",
    "BranchArchived",
    "EmployeeInvited",
    "EmployeeActivated",
    "EmployeeTransferred",
    "EmployeeRemoved",
    "SpeciesCreated",
    "SpeciesUpdated",
    "SpeciesDeleted",
    "PlantVarietyCreated",
    "PlantVarietyUpdated",
    "PlantVarietyDeleted",
    "PlantRegistered",
    "PlantUpdated",
    "PlantStatusChanged",
    "PlantMoved",
    "PlantImageUploaded",
    "PlantArchived",
    "GrowthRecorded",
    "HealthRecorded",
    "WateringRecorded",
    "FertilizerRecorded",
    "EnvironmentalRecorded",
    "DiseaseDetected",
    "DiseaseReportUpdated",
    "TreatmentApplied",
    "InventoryLocationCreated",
    "StockReceived",
    "StockTransferred",
    "StockReserved",
    "StockReleased",
    "StockAdjusted",
    "StockDisposed",
    "StockDamaged",
    "StockSold",
    "InventoryArchived",
    "InventoryMovementRecorded",
    "CustomerCreated",
    "CustomerUpdated",
    "QuotationCreated",
    "QuotationStatusChanged",
    "OrderCreated",
    "OrderStatusChanged",
    "ReservationCreated",
    "ReservationReleased",
    "InvoiceGenerated",
    "PaymentReceived",
    "PlantSold",
    "PlantReturned",
    "RefundProcessed",
    "PassportGenerated",
    "QRGenerated",
    "AIPredictionGenerated",
    "AIPredictionGeneratedForBranch",
    "AIRecommendationGenerated",
    "AIRecommendationDismissed",
    "AIRecommendationActedUpon",
    "AssistantConversationStarted",
    "AssistantMessageSent",
    "AssistantActionProposed",
    "AssistantActionConfirmed",
    "AssistantActionCancelled",
    "PasswordResetRequested",
    "EmailVerificationRequested",
    "SystemAlertRaised",
    "ReservationExpiringSoon",
    "ReportGenerated",
    "ReportFailed",
    "DomainEventPublisher",
    "EventDispatcher",
    "EventHandler",
]
